//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHungdongho.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ChiTietDonHang
    {
        [Key]
        [Display(Name = "Mã Đơn Hàng")]
        public int MaDonHang { get; set; }

        [Key]
        [Display(Name = "Mã Sản Phẩm")]
        public int MaSP { get; set; }

        [Display(Name = "Số Lượng")]
        [Required(ErrorMessage = "Số lượng không được để trống")]
        [Range(1, int.MaxValue, ErrorMessage = "Số lượng phải là một số nguyên dương")]
        public Nullable<int> SoLuong { get; set; }

        [Display(Name = "Giá Sản Phẩm")]
        [Required(ErrorMessage = "Giá sản phẩm không được để trống")]
        [Range(0, double.MaxValue, ErrorMessage = "Giá sản phẩm phải là một số không âm")]
        public Nullable<decimal> GiaSP { get; set; }

        public virtual DonHang DonHang { get; set; }

        public virtual SanPham SanPham { get; set; }
    }
}
