//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHungdongho.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PhanHoi
    {
        [Key]
        [Display(Name = "Mã Phản Hồi")]
        public int MaPhanHoi { get; set; }

        [Display(Name = "Mã Người Dùng")]
        public Nullable<int> MaUser { get; set; }

        [Display(Name = "Nội Dung")]
        [Required(ErrorMessage = "Nội dung phản hồi không được để trống")]
        public string NoiDung { get; set; }

        [Display(Name = "Ngày Phản Hồi")]
        [Required(ErrorMessage = "Ngày phản hồi không được để trống")]
        public Nullable<System.DateTime> NgayPhanHoi { get; set; }

        [Display(Name = "Người Dùng")]
        public virtual User User { get; set; }
    }
}
